InvoicePlatform/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [path('admin/', admin.site.urls), path('', include('users.urls')), path('', include('main.urls'))]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('mainpage/', views.getMainpage, name='getMainpage'),
    path('file/upload/', views.uploadFile, name='uploadFile'),
    path('district/', views.getDistrict, name='getDistrict'),
    path('tags/', views.getSmallTags, name='getSmallTags'),
    path('product/', views.getProducts, name='getProducts'),
    path('draw_buy_with/', views.drawBuyWith, name='drawBuyWith'),
    path('draw_product_in_path/', views.drawPath, name='drawPath'),
    path('rfm/', views.drawRFM, name='drawRFM'),
    path('rfm_with_product/', views.drawRFMwithProduct, name='drawRFMwithProduct'),
    path('info/', views.showInfo, name='showInfo'),
    path('deeper_insight/', views.getDeeperInsight, name='getDeeperInsight'),
    path('analysis/', views.analyze, name='analyze'),
    path('analysisq1/', views.analyzeq1, name='analyzeq1'),
    path('analysisq2/', views.analyzeq2, name='analyzeq2'),
    path('analysisq3/', views.analyzeq3, name='analyzeq3'),
    path('analysisq4/', views.analyzeq4, name='analyzeq4'),
    path('analysisq5/', views.analyzeq5, name='analyzeq5'),
    path('display_overtime/', views.displayOvertime, name='displayOvertime'),
    path('buy_with_in_path/', views.displayBuyWithInPath, name='displayBuyWithInPath'),
    path(
        'buy_with_in_path_networks/<uuid:uu_ID>/',
        views.displayBuyWithInPathNetworks,
        name='displayBuyWithInPathNetworks'
    ),
    path('save_data/', views.saveData, name='saveData'),
    path('stored_picture/', views.getStoredPicture, name='getStoredPicture'),
    path('load_picture/', views.loadPicture, name='loadPicture'),
    path('delete_graph/', views.deleteGraph, name='deleteGraph'),
]

users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# $Id: urls.py 3467 2024-04-21 08:31:00Z Claire $
#
# Copyright (c) 2024 Nuwa Information Co., Ltd, All Rights Reserved.
#
# Licensed under the Proprietary License,
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at our web site.
#
# See the License for the specific language governing permissions and
# limitations under the License.
#
# $Author: Claire $
# $Date: 2024-04-21 16:31:00 +0800 (週日, 21 四月 2024) $
# $Revision: 3467 $
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.getHomePage, name='getHomePage'),
    path('signup/', views.signUp, name='signup'),
    path('login/', views.logIn, name='login'),
    path('logout/', views.logOut, name='logout'),
    path('password/update', views.changePassword, name='resetPassword'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UploadedFile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file_name = models.CharField(max_length=255)
    uploaded_at = models.DateTimeField(auto_now_add=True)


class County(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class District(models.Model):
    name = models.CharField(max_length=100)
    county = models.ForeignKey(County, related_name='districts', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ItemBigTag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class ItemSmallTag(models.Model):
    name = models.CharField(max_length=100)
    bigTag = models.ForeignKey(ItemBigTag, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class NetworkGraph(models.Model):
    name = models.CharField(max_length=500)
    json = models.JSONField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    createdTime = models.DateTimeField(auto_now_add=True)
    csv = models.JSONField()

    def __str__(self):
        return self.name

main/forms.py
# forms.py
import pandas as pd
import openpyxl
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField()

    def clean_file(self):
        file = self.cleaned_data.get('file')
        if not file.name.lower().endswith(('.csv', '.xlsx', '.xls')):
            raise forms.ValidationError('Invalid file format. Only CSV, XLSX, and XLS files are allowed.')

        # Load the file into a pandas DataFrame
        if file.name.lower().endswith('.csv'):
            try:
                df = pd.read_csv(file)
            except Exception as e:
                raise forms.ValidationError(f'Error reading CSV file: {e}')
        else:
            try:
                df = pd.read_excel(file)
            except Exception as e:
                raise forms.ValidationError(f'Error reading Excel file: {e}')

        # Check if required columns exist
        required_columns = [
            'user_id', 'datetime', 'inv_num', 'item_name', 'unit_price', 'quantity', 'amount', 'item_brand_name',
            'store_brand_name', 'county', 'city_area'
        ]

        missing_columns = [col for col in required_columns if col not in df.columns]
        if missing_columns:
            raise forms.ValidationError(f'Missing columns in the file: {", ".join(missing_columns)}')

        # Reset the file pointer to the beginning after reading
        file.seek(0)

        return file

main/views.py
# views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.template.loader import render_to_string
from django.utils.dateparse import parse_date
from .forms import UploadFileForm
from django.http import HttpResponse
from .models import UploadedFile, NetworkGraph
from django.urls import reverse
from .Bert.test import BertModel
import uuid
from .models import County, District, ItemBigTag, ItemSmallTag
from django.http import JsonResponse
import io
import pandas as pd
from .Graph.networks import ProductNetwork, saveJson, compare_node
from .Graph.chatbot import Chatbot
import psycopg2
from django.db import connection
from main import PathList
from decimal import Decimal
import calendar
import json
from django.core.cache import cache
from networkx.readwrite import json_graph
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

BUY_WITH = 1
PRODUCT_IN_PATH = 2
RFM = 3
RFM_WITH_PRODUCT = 4
COUNTRY_DICT = {
    "南投縣": "Nantou",
    "嘉義市": "ChiaYiCity",
    "新北市": "NewTaipei",
    "新竹市": "HsinChuCity",
    "新竹縣": "HsinChuCounty",
    "桃園市": "TaoYuan",
    "澎湖縣": "PengHo",
    "臺中市": "Taichung",
    "臺北市": "Taipei",
    "臺南市": "Tainan",
    "臺東縣": "Taitung",
    "花蓮縣": "HuaLien",
    "苗栗縣": "MiaoLi",
    "金門縣": "KingMen",
    "雲林縣": "YuinLin",
    "高雄市": "KaoHsung",
    "嘉義縣": "ChiaYiCounty",
    "基隆市": "KeeLung",
    "宜蘭縣": "YiLan",
    "屏東縣": "PingTung",
    "彰化縣": "ChungHua",
    "nan": "nan",
}


@login_required
def uploadFile(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.cleaned_data['file']
            if file.name.endswith('.csv'):
                df = pd.read_csv(file)
                b = BertModel()
                df = b.addItemTag(df)
                buffer = io.StringIO()
                df.to_csv(buffer, index=False)
                content = buffer.getvalue()
            else:
                df = pd.read_excel(file)
                b = BertModel()
                df = b.addItemTag(df)
                buffer = io.BytesIO()
                df.to_excel(buffer, index=False, engine='openpyxl')
                content = buffer.getvalue()

            fs = FileSystemStorage(location=settings.MEDIA_ROOT)
            filename = fs.save(
                file.name, io.BytesIO(content.encode('utf-8') if file.name.endswith('.csv') else content)
            )
            UploadedFile.objects.create(user=request.user, file_name=filename)
            fileUrl = fs.url(filename)
            return render(request, 'UploadFile.html', {'form': form, 'fileUrl': fileUrl})
    else:
        form = UploadFileForm()
    return render(request, 'UploadFile.html', {'form': form})


# @login_required
def getMainpage(request):
    return render(request, 'Mainpage123.html')


def getSmallTags(request):
    bigtag = request.GET.get('bigtag')
    smallTags = ItemSmallTag.objects.filter(bigTag__name=bigtag)
    smallTagList = list(smallTags.values('id', 'name'))
    return JsonResponse({'smallTags': smallTagList})


    ###directly select smallTag and Product?
def getProducts(request):
    smallTag = request.GET.get('smallTag')
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT item_name, COUNT(*) 
            FROM test 
            WHERE item_tag = %s 
            GROUP BY item_name
            ORDER BY COUNT(*) DESC
        """, [smallTag]
        )
        rows = cursor.fetchall()

    # 將產品名稱和對應的資料數量一起返回
    products = [{'name': row[0], 'count': row[1]} for row in rows]
    return JsonResponse({'products': products})


def getDistrict(request):
    county = request.GET.get('county')
    districts = District.objects.filter(county__name=county)
    districtList = list(districts.values('id', 'name'))
    return JsonResponse({'districts': districtList})


def _selectArea(request, pictureType):
    counties = County.objects.all()
    print(counties)
    selectedCounty = request.session.get('selectedCounty', '')
    errorMessage = "No"

    if request.method == 'POST':
        county = request.POST.get('county')
        if not county:
            errorMessage = "請選擇縣/市"
        else:
            request.session['selectedCounty'] = county
            if pictureType == BUY_WITH:
                return redirect('/draw_buy_with/?step=select_path_time')
            elif pictureType == PRODUCT_IN_PATH:
                return redirect('/draw_product_in_path/?step=select_time')
            elif pictureType == RFM:
                return redirect('/rfm/?step=select_path_time')
            elif pictureType == RFM_WITH_PRODUCT:
                return redirect('/rfm_with_product/?step=select_path_time')

    return render(
        request, 'Area.html', {
            'counties': counties,
            'selectedCounty': selectedCounty,
            'pictureType': pictureType,
            'errorMessage': errorMessage
        }
    )


###這邊會改成有分類的前幾+交易量前幾###
# def _filterStores(countyName, districtName=None):
#     if districtName:
#         with connection.cursor() as cursor:
#             cursor.execute(
#                 "SELECT DISTINCT store_brand_name FROM test WHERE county = %s AND city_area = %s",
#                 [countyName, districtName]
#             )
#             rows = cursor.fetchall()
#     else:
#         with connection.cursor() as cursor:
#             cursor.execute("SELECT DISTINCT store_brand_name FROM test WHERE county = %s", [countyName])
#             rows = cursor.fetchall()
#     storeBrands = [row[0] for row in rows]

#     return storeBrands


def _filterDistrictsStore(countyName, storeList, itemTag, product=None, minStoreCount=10):
    county = COUNTRY_DICT[countyName]

    # Base SQL query initialization
    query = f"""
        SELECT store_brand_name, COUNT(*) as store_count
        FROM {county}
    """

    # Add condition for store list if provided
    if itemTag:
        query += f"""WHERE a_item_tag = '{itemTag}'"""
        if product:
            if isinstance(product, list):
                # 如果列表中只有一個元素，手動構建單元素元組的格式
                if len(product) == 1:
                    query += f" AND a_item_name = '{product[0]}'"
                else:
                    query += f" AND a_item_name IN {tuple(product)}"
            else:
                # 單個項目時直接用單元素元組的格式
                query += f" AND a_item_name = '{product}'"

        if storeList:
            stores = tuple(storeList)
            query += f" AND store_brand_name IN {stores}"
    else:
        if storeList:
            stores = tuple(storeList)
            query += f" WHERE store_brand_name IN {stores}"

    # Add GROUP BY and HAVING clauses
    query += f"""
        GROUP BY store_brand_name   
    """
    # HAVING COUNT(*) > {minStoreCount}

    # Execute query
    with connection.cursor() as cursor:
        cursor.execute(query) # Pass the parameters dynamically
        result = cursor.fetchall()

    # Extract store_brand_name from the result
    existingStores = [row[0] for row in result]

    return existingStores


def _filterDistrict(countyName):
    if countyName:
        districtList = District.objects.filter(county__name=countyName).values_list('name', flat=True)
        return list(districtList)
    return []


def _filterBigTags(request):
    countyName = request.session.get('selectedCounty', '')
    districtName = request.session.get('districtName', '')
    selectedStartTime = request.session.get('startTime', '')
    selectedEndTime = request.session.get('endTime', '')
    storeTypeList = request.session.get('storeTypeList', '')
    county = COUNTRY_DICT[countyName]
    query = f"SELECT DISTINCT a_item_tag FROM {county}"
    params = []

    hasCondition = False # 标记是否已经添加了第一个条件

    # 动态构建查询条件
    if selectedStartTime:
        query += " WHERE" if not hasCondition else " AND"
        query += f" datetime >= '{selectedStartTime}-01'"
        hasCondition = True # 第一个条件已添加

    if selectedEndTime:
        year, month = map(int, selectedEndTime.split('-'))
        lastDay = calendar.monthrange(year, month)[1]
        query += " WHERE" if not hasCondition else " AND"
        query += f" datetime <= '{selectedEndTime}-{lastDay}'"
        hasCondition = True # 标记已添加条件

    if storeTypeList:
        query += " WHERE" if not hasCondition else " AND"
        query += f" store_brand_name IN {tuple(storeTypeList)}"
        hasCondition = True # 标记已添加条件

    with connection.cursor() as cursor:
        cursor.execute(query, params)
        rows = cursor.fetchall()

    smallTags = [row[0] for row in rows]
    # 暫時反向尋找，之後建立大標籤之欄位
    bigTags = ItemSmallTag.objects.filter(name__in=smallTags).values_list('bigTag__name', flat=True).distinct()
    bigTagsList = list(bigTags)
    return bigTagsList


def _selectPathAndTime(request, pictureType):
    countyName = request.session.get('selectedCounty', '')
    districtName = request.session.get('districtName', '')
    # stores = _filterStores(countyName)

    selectedStartTime = request.session.get('startTime', '')
    selectedEndTime = request.session.get('endTime', '')
    storeType = request.session.get('storeType', '')
    storeTypeList = request.session.get('storeTypeList', '')
    errorMessage = request.GET.get('error_message', '')

    if request.method == 'POST':
        startTime = request.POST.get('startTime')
        endTime = request.POST.get('endTime')
        storeType = request.POST.get('store')
        storeTypeList = PathList.getStoreList(storeType)
        request.session['startTime'] = startTime
        request.session['endTime'] = endTime
        request.session['storeType'] = storeType
        request.session['storeTypeList'] = storeTypeList

        # startDate = parse_date(startTime)

main/templates/main/Analysis.html
{% extends "Mainpage.html" %}

{% block main %}
<div class="container mx-auto py-4">
    <h1 class="text-2xl font-bold text-gray-800">Analysis Result</h1>

    {% if analysis %}
        <!-- 如果有分析結果，顯示結果 -->
        <div class="mt-4 p-4 bg-green-100 border border-green-400 rounded-lg">
            <h2 class="text-lg font-semibold text-green-700">Analysis Output:</h2>
            <p class="text-green-600">{{ analysis }}</p>
        </div>
    {% else %}
        <!-- 如果沒有結果，顯示錯誤訊息 -->
        <div class="mt-4 p-4 bg-red-100 border border-red-400 rounded-lg">
            <p class="text-red-600">{{ error|default:"No analysis result available." }}</p>
        </div>
    {% endif %}
</div>
{% endblock %}

main/templates/main/Area.html
{% extends "Mainpage.html" %}
{% load static %}

{% block main %}
<div class="bg-green-50 flex items-center justify-center min-h-screen">
    <div class="bg-white p-8 md:p-12 rounded-lg shadow-lg w-full max-w-4xl mx-auto ">
        <!-- Progress Bar -->
        
        {% if pictureType == 3  %}
        <div class="mb-8">
            <div class="w-full bg-gray-200 rounded-full h-3 mb-2">
                <div class="bg-green-500 h-3 rounded-full" style="width: 50%;"></div>
            </div>
            <div class="flex justify-around text-base text-gray-500">
                <span class="text-center w-1/2">Step 1: 選擇地區</span>
                <span class="text-center w-1/2">Step 2: 選擇時間和通路</span>
            </div>
        </div>
        {% else %}
        <div class="mb-8">
            <div class="w-full bg-gray-200 rounded-full h-3 mb-2">
                <div class="bg-green-500 h-3 rounded-full" style="width: 33%;"></div>
            </div>
            <div class="flex justify-around text-base text-gray-500">
                <span class="text-center w-1/3">Step 1: 選擇地區</span>
                {% if pictureType == 2 %}
                <span class="text-center w-1/3">Step 2: 選擇時間</span>
                {% else %}
                <span class="text-center w-1/3">Step 2: 選擇時間和通路</span>
                {% endif %}
                <span class="text-center w-1/3">Step 3: 選擇產品分類</span>
            </div>
        </div>
        {% endif %}

        <!-- Title -->
        <h2 class="text-3xl md:text-4xl font-bold text-gray-800 mb-8 text-center">選擇地區</h2>

        {% if pictureType == 1 %}
        <form id="areaForm" method="POST" action="{% url 'main:drawBuyWith' %}?step=select_area" autocomplete="off">
        {% elif pictureType == 2 %}
        <form id="areaForm" method="POST" action="{% url 'main:drawPath' %}?step=select_area" autocomplete="off">
        {% elif pictureType == 3 %}
        <form id="areaForm" method="POST" action="{% url 'main:drawRFM' %}?step=select_area" autocomplete="off">
        {% elif pictureType == 4 %}
        <form id="areaForm" method="POST" action="{% url 'main:drawRFMwithProduct' %}?step=select_area" autocomplete="off">
        {% endif %}
            {% csrf_token %}

            <!-- County Selection with Search -->
            <div class="mb-8 relative">
                <label for="county" class="block text-lg font-medium text-gray-700">縣/市</label>
                <input type="text" id="countyFilter" class="mt-2 block w-full py-3 px-4 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 text-lg" placeholder="搜尋縣/市..." value="{{selectedCounty}}">
                <select id="county" name="county" class="mt-2 block w-full py-3 px-4 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 text-lg" size="5" style="overflow-y: auto; display: none;">
                    {% for county in counties %}
                        <option value="{{ county.name }}" {% if selectedCounty == county.name %}selected{% endif %}>{{ county.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <!-- Error Message -->
            <div id="errorMessage" class="text-red-500 text-sm mb-6" style="display: none;">請選擇縣/市</div>

            <!-- Navigation Buttons -->
            <div class="flex justify-between items-center mt-8">
                <button type="button" onclick="location.href='{% url 'main:getMainpage' %}'" class="px-8 py-4 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 flex items-center text-lg font-medium">
                    <ion-icon name="arrow-back-outline" class="mr-2"></ion-icon>Back to Home
                </button>
                <button type="submit" id="nextButton" class="px-8 py-4 bg-gray-300 text-white rounded-lg flex items-center text-lg font-medium transition-colors duration-200 disabled:bg-gray-300 disabled:text-gray-500" disabled>
                    <ion-icon name="arrow-forward-outline" class="mr-2"></ion-icon>Next
                </button>
            </div>
        </form>
    </div>
</div>
    <script>
          $(document).ready(function() {
            // Filter county options based on input and show dropdown automatically
            $('#errorMessage').hide();
            var selectedCounty = $('#county').val();

            if (selectedCounty) {
                $('#nextButton').prop('disabled', false)
                    .removeClass('bg-gray-300 text-gray-500')
                    .addClass('bg-green-500 text-white');
            } else {
                $('#nextButton').prop('disabled', true)
                    .removeClass('bg-green-500 text-white')
                    .addClass('bg-gray-300 text-gray-500');
            }
            $('#countyFilter').on('input', function() {
                var filterValue = $(this).val().toLowerCase();
                $('#county').show();
                $('#county option').each(function() {
                    $(this).toggle($(this).text().toLowerCase().includes(filterValue));
                });
            });

            $('#countyFilter').on('focus', function() {
                $('#county').show();
            });

            // $('#countyFilter').on('blur', function() {
            //     setTimeout(function() {
            //         $('#county').hide();
            //     }, 200);
            // });

            $('#county').on('change', function() {
                var selectedText = $(this).find("option:selected").text();
                $('#countyFilter').val(selectedText);
                $('#county').hide();
            });

            $('#county').change(function() {
                var county = $(this).val();
                if (county === "") {
                    $('#nextButton').prop('disabled', true)
                        .removeClass('bg-green-500 text-white')
                        .addClass('bg-gray-300 text-gray-500');
                    $('#errorMessage').show(); // 只有當選擇為空時顯示錯誤訊息
                } else {
                    $('#nextButton').prop('disabled', false)
                        .removeClass('bg-gray-300 text-gray-500')
                        .addClass('bg-green-500 text-white');
                    $('#errorMessage').hide();
                }
            });
        });
    </script>


<style>
    #nextButton:disabled {
        cursor: not-allowed;
    }

    #county {
        font-size: 1.25rem;
        padding: 12px;
        border: 1px solid #D1D5DB;
        border-radius: 0.375rem;
        background-color: #fff;
        color: #374151;
        width: 100%;
        max-height: 200px;
        overflow-y: auto;
    }

    #county option {
        padding: 10px;
        font-size: 1.1rem;
    }
</style>

{% endblock %}

main/templates/main/DisplayBuyWithInPathNetworks.html
{% extends "Mainpage.html" %}
{% load static %}
{% block main %}
<iframe src={html} width="100%" height="90%" frameborder="0" allowfullscreen></iframe>

main/templates/main/Mainpage.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice Platform</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/4.6.0/fabric.min.js"></script>
    <style>
      #sidebar {
        margin-top: 56px; 
      }
    </style>
</head>
<body class="bg-gray-100">
  
  <nav class="p-3 bg-white shadow fixed top-0 left-0 w-full z-20">
    <div class="flex justify-between items-center w-full">
      <span class="text-xl font-[Poppins] cursor-pointer">Invoice Platform</span>
      <span class="text-2xl cursor-pointer mx-2 block">
        <ion-icon name="menu" onclick="toggleSidebar()"></ion-icon>
      </span>
    </div>
  </nav>

  <div id="overlay" class="fixed inset-0 bg-black opacity-50 hidden z-10" onclick="closeSidebar()"></div>

  <div class="flex">
    <div id="sidebar" class="w-64 h-screen bg-gray-800 text-white fixed top-0 left-0 transition-transform transform -translate-x-full z-20">
      <ul class="py-4">
        <li class="px-6 py-2">
          <a href="{% url 'main:getMainpage' %}" class="flex items-center space-x-4 hover:bg-gray-700">
            <ion-icon name="home-outline" class="text-2xl"></ion-icon>
            <span>Home</span>
          </a>
        </li>
        <li class="relative px-6 py-2">
          <button onclick="toggleDrawMenu()" class="w-full flex items-center space-x-4 hover:bg-gray-700">
            <ion-icon name="create-outline" class="text-2xl"></ion-icon>
            <span>Network Analysis</span>
          </button>
          <ul id="drawMenu" class="hidden mt-1 bg-gray-700 text-white rounded shadow-lg">
            <li class="px-4 py-2 hover:bg-gray-600">
              <a href="{% url 'main:drawPath' %}">Sales Chanel Analysis</a>
            </li>
            <li class="px-4 py-2 hover:bg-gray-600">
              <a href="{% url 'main:drawBuyWith' %}">Co-Purcahse Analysis</a>
            </li>
          </ul>
        </li>
        <li class="px-6 py-2">
          
          <button onclick="toggleRFMMenu()" class="w-full flex items-center space-x-4 hover:bg-gray-700">
            <ion-icon name="analytics-outline" class="text-2xl"></ion-icon>
            <span>RFM Analysis</span>
          </button>
          <ul id="rfmMenu" class="hidden mt-1 bg-gray-700 text-white rounded shadow-lg">
            <li class="px-4 py-2 hover:bg-gray-600">
              <a href="{% url 'main:drawRFM' %}">General Analysis</a>
            </li>
            <li class="px-4 py-2 hover:bg-gray-600">
              <a href="{% url 'main:drawRFMwithProduct' %}">Tag-Specific Analysis</a>
            </li>
          </ul>
        </li>
        <li class="px-6 py-2">
          <a href="{% url 'main:uploadFile' %}" class="flex items-center space-x-4 hover:bg-gray-700">
            <ion-icon name="cloud-upload-outline" class="text-2xl"></ion-icon>
            <span>Upload Invoice</span>
          </a>
        </li>
        <li class="px-6 py-2">
          <a href="{% url 'main:getStoredPicture' %}" class="flex items-center space-x-4 hover:bg-gray-700">
            <ion-icon name="images-outline" class="text-2xl"></ion-icon>
            <span>Stored Picture</span>
          </a>
        </li>
      </ul>
      <div class="px-6 py-4 mb-0">
        <a href="{% url 'users:logout' %}" class="flex items-center space-x-4 hover:bg-gray-700">
          <ion-icon name="log-out-outline" class="text-2xl"></ion-icon>
          <span>Log Out</span>
        </a>
      </div>
    </div>

    <div class="flex-1 p-10 text-2xl font-bold mt-12">
      {% block main %}
        這邊是Dashboard
      {% endblock %}
    </div>
  </div>

  <script>
    function toggleSidebar() {
      const sidebar = document.getElementById('sidebar');
      const overlay = document.getElementById('overlay');
      sidebar.classList.toggle('-translate-x-full');
      overlay.classList.toggle('hidden');
    }

    function closeSidebar() {
      const sidebar = document.getElementById('sidebar');
      const overlay = document.getElementById('overlay');
      sidebar.classList.add('-translate-x-full');
      overlay.classList.add('hidden');
    }

    function toggleDrawMenu() {
      const drawMenu = document.getElementById('drawMenu');
      drawMenu.classList.toggle('hidden');
    }

    function toggleRFMMenu() {
      const drawMenu = document.getElementById('rfmMenu');
      drawMenu.classList.toggle('hidden');
    }
  </script>
</body>
</html>